name: 'Setup Dojo'
description: 'Setup the Dojo toolchain for use in GitHub Actions'
author: 'DojoEngine'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  version:
    description: 'Version of Dojo to install. If not specified, installs the latest stable version.'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'