name: Test action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dojo
        uses: ./
        id: setup
      - name: Get the installed toolchain version
        run: echo "Installed version ${{ steps.setup.outputs.version }}"
